// src/config/constants.ts
export const CONSTANTS = {
DEFAULT_RADIUS_KM: 0.1,
MIN_RADIUS_KM: 0.1,
MAX_RADIUS_KM: 0.2,
  LOCATION_UPDATE_INTERVAL_MS: 15000, // 15 seconds
  TYPING_DEBOUNCE_MS: 1000,
  TYPING_TIMEOUT_MS: 5000,
  MESSAGE_PAGE_SIZE: 30,
  NEARBY_PAGE_SIZE: 20,
  MAX_BIO_LENGTH: 200,
  MAX_NAME_LENGTH: 50,
  AVATAR_BUCKET: 'avatars',
  OFFLINE_THRESHOLD_MINUTES: 5,
} as const;